name: pretium_finance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  shared_preferences: ^2.3.3
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flex_color_scheme: ^7.2.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
